#!/bin/sh

#
# Le but du script est de créer les différents fichiers de config pour héberger un siteweb  
# Les differentes etapes sont : 
#   - Creer le dossier ou se trouvera le site
#   - Configurer nginx 
#   - Configurer php
#
# syntax
#   wget -q -O - https://raw.github.com/vosprojetsweb/debian-wheezy-webserver-bootstrap/master/lemp/bootstrap-website | sudo /bin/bash -s "server_name"
#   
#
#
# christophe.borsenberger@vosprojetsweb.pro
#

set -e

if [[ $EUID -ne 0 ]]; 
then
   echo "Ce script doit etre lancer en tant que root" >&2
   exit 1
fi

displaytitle() {
    echo -e "\n\n${PURPLE}------------------------------------------------------------------------------"
    echo  "$*"
    echo -e "------------------------------------------------------------------------------${NC}"
}

### Configuration
WGET="wget -m --no-check-certificate -q"
PURPLE='\e[1;35m'
NC='\e[0m'
GIT="https://raw.github.com/vosprojetsweb/debian-wheezy-webserver-bootstrap/master"

SERVER_NAME=${1:?"Erreur. Vous devez fournir le host du site. Ex : www.example.com."}

### TODO : gerer les options pour modifier ces variables
PREFIX_WEBSITE_DIR="/var/www"
PREFIX_GIT_REPO="/var/git"
PREFIX_NGINX_CONFIG="/etc/nginx"
PREFIX_PHP_CONFIG="/etc/php5/"
USERNAME="www-data"

WEBSITE_DIR="${PREFIX_WEBSITE_DIR}/${SERVER_NAME}"
NGINX_CONFIG_FILE="${PREFIX_NGINX_CONFIG}/sites-available/${SERVER_NAME}"
NGINX_CONFIG_LINK="${PREFIX_NGINX_CONFIG}/sites-enabled/${SERVER_NAME}"

PHP_CONFIG_FILE="${PREFIX_PHP_CONFIG}/conf.d/${SERVER_NAME}.ini"
PHP_CONFIG_LINK="${PREFIX_PHP_CONFIG}/fpm/conf.d/99-${SERVER_NAME}.ini"

### Creer le dossier ou se trouvera le site
if [[ ! -d $WEBSITE_DIR ]]
then
    displaytitle "Creation du repertoire ${WEBSITE_DIR}"
    mkdir -p $WEBSITE_DIR
fi

chown -R $USERNAME:$USERNAME $WEBSITE_DIR
chmod -R 2770 $WEBSITE_DIR


### Preparer la configuration nginx
if [[ ! -f $NGINX_CONFIG_FILE ]]
then
    displaytitle "Configuration server nginx ${NGINX_CONFIG_FILE}"
    $WGET -O $NGINX_CONFIG_FILE "${GIT}/lemp/conf/nginx/template.conf"
    sed -i "s|__SERVER_NAME__|${SERVER_NAME}|g" "$NGINX_CONFIG_FILE"
    ln -s $NGINX_CONFIG_FILE $NGINX_CONFIG_LINK
    
    # Si tout est ok avec nginx, on le redemarre
    /usr/sbin/nginx -t
    if [ $? -eq 0 ];
    then
        /etc/init.d/nginx restart
    fi
fi



### Preparer la configuration PHP
if [[ ! -f $PHP_CONFIG_FILE ]]
then
    displaytitle "Configuration PHP-FPM ${PHP_CONFIG_FILE}"
    $WGET -O $PHP_CONFIG_FILE "${GIT}/lemp/conf/php-fpm/template.ini"
    sed -i "s|__SERVER_NAME__|${SERVER_NAME}|g" "$PHP_CONFIG_FILE"
    ln -s $PHP_CONFIG_FILE $PHP_CONFIG_LINK
    
    # Si tout est ok avec nginx, on le redemarre
    /usr/sbin/php5-fpm -t
    if [ $? -eq 0 ];
    then
        /etc/init.d/php5-fpm restart
    fi
fi
